/* 邪恶思潮 · 前端逻辑 v3 */

let currentText='',currentReport=null,imageFile=null,knowledgeGraph=null;

function E(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
var L={has_extreme_numbers:'极端数字',has_urgency_call:'紧急呼吁',has_emotional_trigger:'情绪触发',has_authority_claim:'声称权威',has_identity_binding:'身份绑定',has_visual_description:'画面描述',has_conspiracy_hint:'阴谋暗示',has_total_negation:'全称否定',has_vague_time_place:'时空模糊',has_call_to_action:'行动号召',has_numeric_claim:'数据声明',has_moral_judgment:'道德评判',has_us_vs_them:'对立叙事',has_health_fear:'健康恐慌'};
var defTexts=['等待输入','等待指纹官完成','等待侦察取证完成','等待仲裁官完成'];

function setAgent(i,s,t){var el=document.getElementById('agent'+(i+1)+'-status');if(el){el.textContent=t||(s==='loading'?'分析中...':s==='success'?'✓ 完成':defTexts[i]);el.className='text-xs ml-auto '+(s==='loading'?'text-purple-400 animate-pulse':s==='success'?'text-green-400':'text-gray-500')}
  var p=document.getElementById('agent'+(i+1)+'-panel');if(p){p.classList.remove('opacity-50');if(s==='loading')p.classList.add('active');if(s==='success'){p.classList.remove('active');p.classList.add('complete')}}
  var bar=document.getElementById('agent'+(i+1)+'-progress');if(bar){var d=bar.querySelector('div');if(d)d.style.width=s==='waiting'?'0%':s==='loading'?'60%':'100%'}
  var c=document.getElementById('agent'+(i+1)+'-content');if(c&&s!=='waiting')c.classList.remove('hidden')}
function setContent(i,h){var c=document.getElementById('agent'+(i+1)+'-content');if(c){c.innerHTML=h;c.classList.remove('hidden')}}
function addContent(i,h){var c=document.getElementById('agent'+(i+1)+'-content');if(c){c.innerHTML+=h;c.classList.remove('hidden')}}
function resetAll(){for(var i=0;i<4;i++){setAgent(i,'waiting',defTexts[i]);var c=document.getElementById('agent'+(i+1)+'-content');if(c){c.innerHTML='';c.classList.add('hidden')}var p=document.getElementById('agent'+(i+1)+'-panel');if(p){p.classList.add('opacity-50');p.classList.remove('active','complete','skipped')}}
  document.getElementById('progress-section').classList.remove('hidden');document.getElementById('report-section').classList.add('hidden')}

function handleSSE(d){var evt=d.event,agent=d.agent,data=d.data;
  if(evt==='fingerprint'){setAgent(0,'loading','指纹提取中...');var fp=data.fingerprint||{},fs=fp.features||{};var tags=Object.entries(fs).filter(function(e){return e[1]}).slice(0,8).map(function(e){return'<span class="inline-block px-2 py-0.5 rounded text-xs bg-gray-700/50 text-red-400 border border-gray-600 mr-1 mb-1">'+(L[e[0]]||e[0])+'</span>'}).join('');setContent(0,'<div class="flex flex-wrap mb-2">'+tags+'</div><div class="text-gray-300 text-xs">'+E(data.summary||'')+'</div>')}
  else if(evt==='behavior_motivation'){setAgent(0,'loading','行为分析中...');var b=data.behavior||{},m=data.motivation||{};addContent(0,'<div class="text-gray-300 text-xs mt-2 pt-2 border-t border-gray-700">行为: '+E((b.manipulation_style||'').substring(0,80))+'<br>动机: '+E(m.motive_category||'')+'</div>')}
  else if(evt==='cognitive_warfare'){setAgent(0,'loading','认知战检测中...');var t=data.matched_templates||[];if(t.length){var h='<div class="mt-2 p-3 bg-red-900/10 rounded-lg border border-red-800/30"><div class="text-red-400 font-medium text-xs">🛡️ 认知战: '+(data.threat_level||'')+' · '+(data.template_count||0)+'种模式</div>';t.forEach(function(t){h+='<div class="text-gray-300 text-xs mt-1"><b>'+E(t.name)+'</b>: '+E(t.description)+'</div>'});h+='</div>';addContent(0,h)}}
  else if(evt==='kb_assist'){setAgent(0,'loading','KB匹配中...');addContent(0,'<div class="text-blue-400 text-xs mt-1">📚 KB辅助: '+(data.match_count||0)+'个案例</div>')}
  else if(evt==='keywords_extracted'){var fc=data.fact_check_keywords||[],ds=data.deep_search_keywords||[],sc=data.source_check_keywords||[];var h='<div class="mt-2 pt-2 border-t border-gray-700"><div class="text-green-400 text-xs font-medium mb-1">🎯 指纹官提炼关键词 → 传递三路侦察兵</div>';if(fc.length){h+='<div class="text-xs text-blue-300 mt-1">🔍 事实核查: ';fc.forEach(function(k){h+='<span class="inline-block bg-blue-900/30 rounded px-1.5 py-0.5 mr-1 border border-blue-800/30">'+E(k)+'</span>'});h+='</div>'}if(ds.length){h+='<div class="text-xs text-orange-300 mt-1">📄 深度挖掘: ';ds.forEach(function(k){h+='<span class="inline-block bg-orange-900/30 rounded px-1.5 py-0.5 mr-1 border border-orange-800/30">'+E(k)+'</span>'});h+='</div>'}if(sc.length){h+='<div class="text-xs text-green-300 mt-1">✅ 来源验证: ';sc.forEach(function(k){h+='<span class="inline-block bg-green-900/30 rounded px-1.5 py-0.5 mr-1 border border-green-800/30">'+E(k)+'</span>'});h+='</div>'}h+='</div>';addContent(0,h)}
  else if(evt==='ocr_start'){setAgent(0,'loading','OCR提取中...');setContent(0,'<div class="text-gray-300 text-xs">🤖 OCR文字提取中...</div>')}
  else if(evt==='ocr_complete'){setAgent(0,'success','✓ OCR完成');setContent(0,'<div class="text-green-400 text-xs">✅ OCR完成: '+(data.length||0)+'字符</div><div class="bg-gray-800 rounded-lg p-3 mt-2 max-h-32 overflow-y-auto text-xs text-gray-300 whitespace-pre-wrap">'+E((data.text||'').substring(0,500))+'</div>');document.getElementById('input-text').value=data.text||'';currentText=data.text||''}
  else if(evt==='agent_start'){if(agent==='fp_team')setAgent(0,'loading','5专家并行研判+提炼关键词...');else if(agent==='malice'||agent==='debater')setAgent(2,'loading','辩论裁定中...');else if(agent==='jury')setAgent(2,'loading','合议庭审议中...');else if(agent==='chief_judge')setAgent(2,'loading','首席裁定中...');else if(agent==='recon')setAgent(1,'loading','并行取证中...');else if(agent==='publisher')setAgent(3,'loading','生成报告中...');else if(agent==='evaluator')setAgent(3,'loading','品质审核中...')}
  else if(evt==='agent_complete'){
    if(agent==='malice'){setAgent(0,'success','✓ 分析完成');var v=data.evil_score||0,c=v>=0.7?'text-red-400':v>=0.4?'text-orange-400':'text-green-400';addContent(0,'<div class="mt-2 pt-2 border-t border-gray-700"><div class="text-gray-200 text-xs bg-gray-700/50 rounded-lg p-2">🔮 '+E((data.malice_hypothesis||'').substring(0,200))+'</div><div class="flex gap-4 mt-2 text-xs"><span class="text-gray-300">邪恶评分: <b class="'+c+'">'+(v*100).toFixed(0)+'%</b></span><span class="text-gray-300">攻击: '+E(data.primary_attack||'')+'</span></div></div>')}
    else if(agent==='debater'){setAgent(2,'success','✓ 裁定完成');var cv=data.cross_validation||{},fv=data.final_verdict||{};var h='<div class="grid grid-cols-4 gap-2 mb-2"><div class="text-center bg-gray-800 rounded-lg p-2"><div class="text-blue-400 font-bold">'+(cv.total_sources||0)+'</div><div class="text-gray-400 text-xs">总信源</div></div><div class="text-center bg-gray-800 rounded-lg p-2"><div class="text-green-400 font-bold">'+(cv.agreeing_sources||0)+'</div><div class="text-gray-400 text-xs">印证</div></div><div class="text-center bg-gray-800 rounded-lg p-2"><div class="text-yellow-400 font-bold">'+(cv.quality||'?')+'</div><div class="text-gray-400 text-xs">质量</div></div><div class="text-center bg-gray-800 rounded-lg p-2"><div class="text-red-400 font-bold">'+((fv.confidence||0)*100).toFixed(0)+'%</div><div class="text-gray-400 text-xs">置信</div></div></div>';(data.consensus||{}).confirmed&&(data.consensus.confirmed||[]).forEach(function(c){h+='<div class="text-xs text-green-400 ml-2">✓ '+E(c)+'</div>'});(data.consensus||{}).disputed&&(data.consensus.disputed||[]).forEach(function(c){h+='<div class="text-xs text-red-400 ml-2">✗ '+E(c)+'</div>'});setContent(2,h)}
    else if(agent==='publisher'){setAgent(3,'success','✓ 报告生成');var h='<div class="text-green-400 text-xs">📝 报告已生成，品质审核中...</div>';setContent(3,h)}
    else if(agent==='evaluator'){setAgent(3,'success','✓ 审核完成');var q=data.quality_score||0,dim=data.dimensions||{};var h='<div class="text-xs text-gray-300">品质: <b class="text-white">'+(q*100).toFixed(0)+'%</b></div><div class="grid grid-cols-2 gap-2 mt-2 text-xs">';['evidence_sufficiency','confidence_reasonability','completeness','rigor'].forEach(function(k){var lb={evidence_sufficiency:'证据充分',confidence_reasonability:'置信合理',completeness:'核查完整',rigor:'结论严谨'};h+='<div class="text-center bg-gray-800 rounded-lg p-2"><div class="text-gray-400">'+lb[k]+'</div><div class="text-white font-bold">'+((dim[k]||0)*100).toFixed(0)+'%</div></div>'});h+='</div>';if(data.final_assessment)h+='<div class="text-yellow-200 text-xs mt-2 bg-yellow-900/20 rounded-lg p-2">'+E(data.final_assessment)+'</div>';setContent(3,h)}}
  else if(evt==='fp_team_complete'){setAgent(0,'loading','专家研判完成');var fp=data.fp_verdict||{};var ev=data.evo_verdict||{};var it=data.intent_verdict||{};var ri=data.risk_verdict||{};addContent(0,'<div class="grid grid-cols-2 gap-2 mt-2 pt-2 border-t border-gray-700 text-xs"><div class="bg-gray-800 rounded p-2"><div class="text-blue-300 font-medium">🧬 指纹对比</div><div class="text-gray-400">'+E((fp.fingerprint_verdict||'').substring(0,60))+'</div></div><div class="bg-gray-800 rounded p-2"><div class="text-green-300 font-medium">🌳 进化树</div><div class="text-gray-400">'+E((ev.evolution_analysis||'').substring(0,60))+'</div></div><div class="bg-gray-800 rounded p-2"><div class="text-purple-300 font-medium">🔍 意图挖掘</div><div class="text-gray-400">'+E((it.primary_intent||'').substring(0,60))+'</div></div><div class="bg-gray-800 rounded p-2"><div class="text-red-300 font-medium">⚠️ 风险评估</div><div class="text-gray-400">'+(ri.public_opinion_risk||'')+'</div></div></div>')}
  else if(evt==='parallel_start'){setAgent(1,'loading','并行取证中...');setContent(1,'<div class="text-blue-300 text-xs">🔍 并行取证: Claude事实核查 + Claude深度挖掘 + 来源验证</div>')}
  else if(evt==='parallel_complete'){setAgent(1,'success','✓ 取证完成');var ags=[['Claude事实核查',data.findings_checker||{}],['Claude深度挖掘',data.findings_diver||{}],['来源验证',data.findings_osint||{}]];var ac=['#1d4ed8','#c2410c','#15803d'];var h='<div class="grid grid-cols-3 gap-2">';ags.forEach(function(a,i){h+='<div class="rounded-lg p-3 text-center border" style="border-color:'+ac[i]+';background:'+ac[i]+'10"><div style="color:'+ac[i]+';font-weight:700;font-size:.8rem">'+a[0]+'</div><div class="text-gray-600 text-xs mt-1">'+((a[1].findings||[]).length)+'个发现</div><div class="text-gray-500 text-xs">'+E((a[1].summary||'').substring(0,40))+'</div></div>'});h+='</div>';setContent(1,h)}
  else if(evt==='search_trace'){var urls=[];(data.agents||[]).forEach(function(a){(a.sources||[]).forEach(function(s){if(s.url&&(s.url.indexOf('http://')===0||s.url.indexOf('https://')===0))urls.push({t:(s.title||s.url).substring(0,80),u:s.url,ss:(s.snippet||'').substring(0,120),an:a.name})})});if(urls.length){var h='<div class="mt-2 pt-2 border-t border-gray-700"><div class="text-green-400 text-xs font-medium mb-1">🔗 搜索溯源 · 可点击验证 ('+urls.length+'个真实来源)</div>';urls.slice(0,8).forEach(function(s){h+='<div class="text-xs mb-1 p-1.5 bg-gray-800/50 rounded"><span class="text-gray-500">['+E(s.an)+']</span> <a href="'+E(s.u)+'" target="_blank" class="text-blue-400 hover:underline">🔗 '+E(s.t)+'</a>'+(s.ss?'<div class="text-gray-500 ml-3">"'+E(s.ss)+'"</div>':'')+'</div>'});h+='</div>';addContent(1,h)}}
  else if(evt==='jury_complete'){var v1=(data.verdict_1||{}).final_verdict||{};var v2=(data.verdict_2||{}).final_verdict||{};var v3=(data.verdict_3||{}).final_verdict||{};addContent(2,'<div class="text-yellow-300 text-xs mt-2 pt-2 border-t border-gray-700">⚖️ 合议庭: 仲裁官1='+(v1.conclusion||'?')+'('+((v1.confidence||0)*100).toFixed(0)+'%) | 仲裁官2='+(v2.conclusion||'?')+'('+((v2.confidence||0)*100).toFixed(0)+'%) | 仲裁官3='+(v3.conclusion||'?')+'('+((v3.confidence||0)*100).toFixed(0)+'%)</div>')}
  else if(evt==='report')showReport(data);
  else if(evt==='knowledge_hit'){setAgent(2,'success','📚 知识库命中');setContent(2,'<div class="verdict-row"><span class="verdict-label fake">✗ 伪造</span><span class="verdict-confidence">相似度 '+((data.similarity||0)*100).toFixed(0)+'%</span></div><div class="card-text text-gray-300">知识库已核查: '+E(data.verdict||'')+'</div>');showReportSection()}
  else if(evt==='done')loadKBStats();
  else if(evt==='error')alert(data.message||'未知错误')}

function showReport(data){currentReport=data;showReportSection();var v=data.overall_verdict||'';var isFake=v.includes('false')||v.includes('manipulative');
  var card=document.getElementById('verdict-card');card.className='rounded-2xl p-6 border-2 '+(isFake?'verdict-false':v.includes('true')?'verdict-true':v.includes('suspicious')?'verdict-suspicious':'verdict-unknown');
  document.getElementById('verdict-label').textContent=isFake?'❌ 虚假信息':v.includes('true')?'✅ 信息属实':v.includes('manipulative')?'⚠️ 认知操纵':v.includes('suspicious')?'🟡 信息存疑':'⚪ 无法判定';
  document.getElementById('verdict-meta').innerHTML='<div class="text-white font-medium">'+E(data.one_sentence_verdict||'')+'</div><div>邪恶评分: <b>'+((data.evil_score||0)*100).toFixed(0)+'%</b> · 置信度: <b>'+((data.confidence||0.8)*100).toFixed(0)+'%</b></div>';
  if(data.malice_hypothesis){var mh=document.getElementById('malice-hypothesis');mh.classList.remove('hidden');mh.innerHTML='<span class="text-purple-300 font-medium">🔮 恶意假设：</span>'+E(data.malice_hypothesis)}
  var rx=data.prescription||{};var ps=document.getElementById('prescription-section');var pc=document.getElementById('prescription-content');
  if(rx.how_deceived&&rx.how_deceived.length||rx.prevention&&rx.prevention.length){ps.classList.remove('hidden');var h='';if(rx.how_deceived&&rx.how_deceived.length){h+='<div><h4 class="text-sm font-medium text-yellow-200 mb-2">怎么骗你的？</h4>';rx.how_deceived.forEach(function(s){h+='<div class="text-sm text-gray-300">· '+E(s)+'</div>'});h+='</div>'}if(rx.prevention&&rx.prevention.length){h+='<div class="mt-3"><h4 class="text-sm font-medium text-yellow-200 mb-2">怎么防？</h4>';rx.prevention.forEach(function(s){h+='<div class="text-sm text-gray-300">· '+E(s)+'</div>'});h+='</div>'}pc.innerHTML=h}else{ps.classList.add('hidden')}
  var dc=data.debunk_card||{};var ds=document.getElementById('debunk-section');var dcc=document.getElementById('debunk-content');
  if(dc.headline){ds.classList.remove('hidden');dcc.innerHTML='<div class="text-yellow-200 text-sm font-medium">'+E(dc.headline)+'</div><div class="space-y-2 mt-2"><div><span class="text-xs text-gray-500">❌ </span><span class="text-red-400 text-sm line-through">'+E(dc.fake_claim||'')+'</span></div><div><span class="text-xs text-gray-500">✅ </span><span class="text-green-400 text-sm font-medium">'+E(dc.truth||'')+'</span></div>'+(dc.source?'<div class="text-xs text-blue-300">📎 来源：'+E(dc.source)+'</div>':'')+'</div>'}else{ds.classList.add('hidden')}
  try{renderEvidenceGraph(data)}catch(e){}
  var kb=document.getElementById('kb-info');if(kb){kb.innerHTML='<div class="flex gap-6 text-sm"><div>📊 交叉验证: <b class="text-green-400">'+(data.cross_validation_count||0)+'</b> 个独立信源</div><div>🛡️ 基于双Claude+来源验证三方真实搜索交叉验证</div></div>'}
  document.getElementById('report-section').scrollIntoView({behavior:'smooth',block:'start'})}
function showReportSection(){document.getElementById('report-section').classList.remove('hidden')}

function renderEvidenceGraph(data){
  var el=document.getElementById('evidence-graph');if(!el||!vis)return;el.innerHTML='';el.style.height='350px';
  var chain=data.evidence_chain||[];if(!chain.length)return;
  var V={false:{bg:'#ef4444',bd:'#f87171'},true:{bg:'#22c55e',bd:'#4ade80'},partial:{bg:'#eab308',bd:'#facc15'},unverifiable:{bg:'#6b7280',bd:'#9ca3af'}};
  var nodes=[],edges=[];
  nodes.push({id:'root',label:'📋 待核查',shape:'box',size:28,color:{background:'#1e40af',border:'#3b82f6'},font:{color:'#fff',size:13,face:'sans-serif'},borderWidth:3});
  chain.forEach(function(e,i){var v=e.verdict||'unverifiable';var vc=V[v]||V.unverifiable;var fid='f'+i,sid='s'+i,cid='c'+i;
    nodes.push({id:fid,label:(e.description||e.claim_text||'').substring(0,25),shape:'box',size:20,color:{background:'#1e293b',border:vc.bd},font:{color:'#e2e8f0',size:11}});
    edges.push({from:'root',to:fid,color:{color:vc.bd,opacity:.6},width:2});
    nodes.push({id:sid,label:'📎 '+(e.source||'来源').substring(0,18),shape:'dot',size:16,url:e.source_url||'',color:{background:'#0f766e',border:'#14b8a6'},font:{color:'#99f6e4',size:10},title:(e.source||'')+(e.source_url?'\n双击打开':'')});
    edges.push({from:fid,to:sid,dashes:[6,3],color:{color:'#14b8a6',opacity:.5},width:1});
    nodes.push({id:cid,label:v==='false'?'❌':v==='true'?'✅':'⚠️',shape:'diamond',size:18,color:{background:vc.bg,border:vc.bd},font:{color:'#fff',size:12,bold:true}});
    edges.push({from:sid,to:cid,color:{color:vc.bd,opacity:.8},width:3});
    if(i>0&&(chain[i-1].verdict||'')===v){edges.push({from:'c'+(i-1),to:cid,color:{color:'#22c55e',opacity:.1},width:1,dashes:[4,4],title:'交叉验证'})}
  });
  var g=new vis.Network(el,{nodes:new vis.DataSet(nodes),edges:new vis.DataSet(edges)},{nodes:{borderWidth:2,shadow:{enabled:true,size:3}},edges:{smooth:{type:'curvedCW',roundness:.25}},physics:{solver:'forceAtlas2Based',forceAtlas2Based:{gravitationalConstant:-100,centralGravity:.01,springLength:180,springConstant:.05,damping:.5},stabilization:{iterations:100}},interaction:{hover:true,zoomView:true,dragView:true}});
  g.on('doubleClick',function(p){if(p.nodes.length){var n=nodes.get(p.nodes[0]);if(n&&n.url)window.open(n.url,'_blank')}});
}

function startAnalysis(){var t=document.getElementById('input-text').value.trim();if(!t&&!imageFile)return alert('请先输入信息或上传图片');resetAll();currentText=t||'';currentReport=null;var btn=document.getElementById('btn-analyze');btn.disabled=true;btn.textContent='⏳ 核查中...';window.scrollTo({top:0,behavior:'smooth'});
  var p;if(imageFile){var fd=new FormData();fd.append('file',imageFile);p=fetch('/api/analyze-image',{method:'POST',body:fd})}else{p=fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:t})})}
  p.then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);var reader=r.body.getReader(),decoder=new TextDecoder(),buf='';function read(){reader.read().then(function(_r){var done=_r.done,value=_r.value;if(done)return;buf+=decoder.decode(value,{stream:true});var lines=buf.split('\n');buf=lines.pop()||'';lines.forEach(function(l){if(!l.startsWith('data: '))return;try{handleSSE(JSON.parse(l.slice(6)))}catch(e){}});read()})}read()}).catch(function(e){alert('失败: '+e.message)}).finally(function(){btn.disabled=false;btn.textContent='🔍 开始核查';loadKBStats()})}
function copyReport(){if(!currentReport)return;var r=currentReport,dc=r.debunk_card||{};var t=['邪恶思潮 · 核查报告','判定: '+(r.verdict_display||''),'置信度: '+((r.confidence||0.8)*100).toFixed(0)+'%',dc.headline?'辟谣: '+dc.headline:'',dc.truth?'真相: '+dc.truth:'',dc.source?'来源: '+dc.source:'','核查编号: '+(r.id||'')].filter(Boolean).join('\n');navigator.clipboard.writeText(t)}
function sendFeedback(c){if(!currentText)return;fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:currentText,is_correct:c})})}
function handleImageSelect(e){var f=e.target.files[0];if(f){imageFile=f;var u=URL.createObjectURL(f);document.getElementById('image-preview').classList.remove('hidden');document.getElementById('image-preview-img').src=u}}
function clearImage(){imageFile=null;document.getElementById('image-preview').classList.add('hidden');document.getElementById('input-image').value=''}
function switchView(v){document.getElementById('view-check').style.display=v==='check'?'block':'none';var gs=document.getElementById('graph-section');if(gs)gs.classList.toggle('hidden',v!=='graph');document.getElementById('btn-view-check').className='px-3 py-1.5 rounded-lg '+(v==='check'?'bg-blue-600 text-white':'bg-gray-800 text-gray-400 hover:text-white')+' font-medium transition-colors';document.getElementById('btn-view-graph').className='px-3 py-1.5 rounded-lg '+(v==='graph'?'bg-blue-600 text-white':'bg-gray-800 text-gray-400 hover:text-white')+' font-medium transition-colors';if(v==='graph')loadGraph()}
function loadGraph(){var c=document.getElementById('knowledge-graph');if(!c||knowledgeGraph)return;fetch('/api/knowledge/graph').then(function(r){return r.json()}).then(function(d){knowledgeGraph=new vis.Network(c,{nodes:new vis.DataSet(d.nodes||[]),edges:new vis.DataSet(d.edges||[])},{nodes:{borderWidth:2,shadow:{enabled:true,size:3}},edges:{smooth:{type:'continuous',roundness:.5}},physics:{solver:'forceAtlas2Based',forceAtlas2Based:{gravitationalConstant:-80,centralGravity:.01,springLength:180,springConstant:.08}},groups:{attack_dimension:{shape:'diamond',color:{background:'#7c3aed',border:'#a78bfa'},font:{color:'#c4b5fd'}},category:{shape:'dot',size:28,font:{color:'#93c5fd'}},case:{shape:'box',font:{color:'#e5e7eb',size:11}}}});setTimeout(function(){knowledgeGraph.fit({animation:true})},500)}).catch(function(){})}
function loadKBStats(){fetch('/api/knowledge/stats').then(function(r){return r.json()}).then(function(s){document.getElementById('kb-stats').textContent='📚 '+s.total_cases+'条'}).catch(function(){})}
loadKBStats();
document.addEventListener('paste',function(e){var i=e.clipboardData?.items[0];if(i&&i.type.startsWith('image/')){e.preventDefault();imageFile=i.getAsFile();var u=URL.createObjectURL(imageFile);document.getElementById('image-preview').classList.remove('hidden');document.getElementById('image-preview-img').src=u}});
document.getElementById('btn-feedback-yes').addEventListener('click',function(){var s=document.getElementById('feedback-status');sendFeedback(true);s.classList.remove('hidden');s.textContent='✅ 感谢反馈！'});
document.getElementById('btn-feedback-no').addEventListener('click',function(){var s=document.getElementById('feedback-status');sendFeedback(false);s.classList.remove('hidden');s.textContent='📝 感谢反馈！'});
document.getElementById('btn-copy').addEventListener('click',function(){copyReport();var s=document.getElementById('copy-status');s.classList.remove('hidden');setTimeout(function(){s.classList.add('hidden')},2000)});
document.getElementById('btn-clear-image').addEventListener('click',clearImage);
